services:
- type: web
  name: line-bot-python-cocobot
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: python CocoBot.py
  plan: free
  autoDeploy: false
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false